version: '3'
services:
  mysql:
    container_name: ohmyies-mysql
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: ohmyies
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    command:
      - '--skip-log-bin'
    ports:
      - "3307:3306"
    networks:
      - ohmyies-network
  php:
    container_name: ohmyies-php
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    volumes:
      - ./public:/OhMyIES/public
      - ./app:/OhMyIES/app
      - ./conf.json:/OhMyIES/conf.json
    depends_on:
      - mysql
    networks:
      - ohmyies-network
networks:
  ohmyies-network:
    driver: bridge
